# Generated by Django 3.0.5 on 2021-06-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderprocessstaffuserid',
            field=models.ForeignKey(blank=True, db_column='OrderProcessStaffUserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Orderprocessstaff'),
        ),
    ]
