# Generated by Django 3.0.5 on 2021-06-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customeruserid',
            field=models.ForeignKey(db_column='CustomerUserID', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='voucherid',
            field=models.ForeignKey(blank=True, db_column='VoucherID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Voucher'),
        ),
    ]
