# Generated by Django 3.0.5 on 2021-06-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210602_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customeruserid',
            field=models.ForeignKey(blank=True, db_column='CustomerUserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
        ),
    ]
