# Generated by Django 3.0.5 on 2021-06-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='historylineid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxid',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='discountamount',
        ),
        migrations.AddField(
            model_name='voucher',
            name='maxamount',
            field=models.IntegerField(blank=True, db_column='MaxAmount', null=True),
        ),
        migrations.AlterField(
            model_name='historyline',
            name='orderinfo',
            field=models.ForeignKey(db_column='OrderID', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='delaydate',
            field=models.IntegerField(blank=True, db_column='DelayDate', null=True),
        ),
    ]
