# Generated by Django 3.0.5 on 2021-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210602_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=255, null=True),
        ),
    ]
