from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(Account)
admin.site.register(Address)
admin.site.register(Book)
admin.site.register(BookGenre)
admin.site.register(Businessstaff)
admin.site.register(Card)
admin.site.register(Cartline)
admin.site.register(Cash)
admin.site.register(Category)
admin.site.register(Clothes)
admin.site.register(Contactinfo)
admin.site.register(Customer)
admin.site.register(Customerreview)
admin.site.register(Electronic)
admin.site.register(Feedback)
admin.site.register(Fullname)
admin.site.register(Genre)
admin.site.register(Historyline)
admin.site.register(Importingrecord)
admin.site.register(Importingline)
admin.site.register(Item)
admin.site.register(Membershiptype)
admin.site.register(Order)
admin.site.register(Orderhistory)
admin.site.register(Orderprocessstaff)
admin.site.register(Payment)
admin.site.register(Producer)
admin.site.register(Product)
admin.site.register(Promotion)
admin.site.register(PromotionItem)
admin.site.register(Qrcode)
admin.site.register(Salesstaff)
admin.site.register(Shippingaddress)
admin.site.register(Shippinginfo)
admin.site.register(Shoppingcart)
admin.site.register(Staffs)
admin.site.register(Supplier)
admin.site.register(Tax)
admin.site.register(User)
admin.site.register(Voucher)
admin.site.register(Warehousestaff)